

## List of group pairs to compare for alternative splicing analysis
diff_pair_list:
    Sample1_vs_Sample2:
        - Sample1
        - Sample2
    Sample2_vs_Sample3:
        - Sample1
        - Sample3
    Sample1_vs_Sample3:
        - Sample2
        - Sample3

## path to sample file
src_sampleInfo: "sample.tsv"

directory:
    ## reference directory that contains reference FA files, index, bed etc.
    ref_dir: "/data/limlab/Resource/BisKit_Reference/mm10"

    ## output directory names; recommended to use default
    fastq_dir: "0.Fastq"
    trim_dir: "0.Fastq.Trim"
    sample_dir: "1.Sample"
    plot_dir: "1.Sample_Plots"
    compare_dir: "2.Diff"
    combined_compare_dir: "3.Final_Results"
    mqc_dir: "4.multiQC"


options:
    ## deduplication
    doDedup: False

    ## softclipping during alignment; enter 'True' to allow soft-clipping or 'False' to prevent soft-clipping, without the quotation marks
    soft_clipping: True

    ## Set genome spliced alignment
    Allow_genome_spliced_alignment: True

    ## Set RNA spliced alignment
    Allow_RNA_spliced_alignment: False


## parameters
params:
    ## adapter trimming; set adapter: "NULL" if you do not want to perform trimming.
    ## Multiple adapter sequences can be added; check the default entry below
    ## illumina universal adapter = "AGATCGGAAGAGC"
    ## illumina small RNA adapter = "TGGAATTCTCGGGTGCCAAGG"
    ## Nextera adapter for ATAC-seq or Cut&Tag = "CTGTCTCTTATA"
    adapter: ["AGATCGGAAGAGC", "TGGAATTCTCGGGTGCCAAGG"]

    ## additional options for cutadapt; follow cutadapt syntax. Leave as empty quotes if no additional options are being used.
    ## default parameters: minimum fragment length 18, minimum quality 20 for quality trimming
    opt_cutadapt: "--minimum-length 18 -q 20"

    ## Regular expressions for target chromosomes
    chrRegex: "^chr[0-9XY]+$"
    chrRegexTarget: "^chr[0-9XY]+$"

    ## threshold for minimum coverage for a C to be considered a potential candidate
    coverage_threshold: 10
    
    ## threshold for minimum methylation rate for a C to be considered a potential candidate
    methylation_rate_threshold: 0.1
    
    ## threshold for minimum difference between two samples at a C location to be considered a significant candidate
    differential_threshold: 0.05

    ## type of statistical significant to be used for the call step; it can be either 'pVal' or 'FDR'
    statistical_significance_call: pVal
    
    ## value of statistical threshold for the call step
    statistical_threshold_call: 0.05
    
    ## minimum replicates a C position has to be seen to be considered a candidate. Enter the value '1' if you have no replicates.
    ## The number of sample replicates should always be higher than or equal to the number of control replicates.
    minimum_replicates: 2

    ## minimum C count needed for a C position to be considered a candidate
    minimum_C_count: 3

    ## type of statistical significant to be used for the call step; it can be either 'pVal' or 'FDR'
    statistical_significance_diff: pVal
    
    ## value of statistical threshold for the call step
    statistical_threshold_diff: 0.05